name: Get new ratings
on:
  schedule:
  - cron: "30 10 * * 4"
env:
  SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
  UNTAPPD_ACCESS_TOKEN: ${{ secrets.UNTAPPD_ACCESS_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
