name: Get new ratings
on: 
    push:
      branches:
        - main  
    schedule:
      - cron: "0 * * * *"
  
env:
  SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
  UNTAPPD_ACCESS_TOKEN: ${{ secrets.UNTAPPD_ACCESS_TOKEN }}

jobs:
  execute:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install hatch
        run: pip install hatch
      - name: Run tests
        run: hatch run test:tests
      - name: Run script
        run: hatch run shopitappd
        shell: sh
